name: learn_rpl
description: A new Flutter project.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.2.1
  firebase_auth_web: ^5.13.0
  firebase_core: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo1.png

